services:
  postgres:
    image: postgres:16
    container_name: records_management_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: records_user26
      POSTGRES_PASSWORD: records_password26
      POSTGRES_DB: records_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: